[build]
builder = "NIXPACKS"
buildCommand = "npm install --workspace=web --workspace=@uteq/shared --include-workspace-root && npm run build --workspace=web"
watchPatterns = ["apps/web/**", "packages/shared/**"]

[deploy]
startCommand = "npm run start --workspace=web"
healthcheckPath = "/login"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
